name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  workflow_call:
    inputs:
      revision:
        required: true
        type: string
    secrets:
      PYPI_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ inputs.revision || github.sha }}
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "${{ matrix.python-version }}"
        cache: pip
    - name: Build python package
      shell: sh
      run: |
        pip install build==0.10.0
        python -m build
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: dist-python${{ matrix.python-version }}
        path: dist

  publish:
    concurrency: publish
    needs: [build]
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.10"
    steps:
      - uses: actions/download-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dist-python${{ env.PYTHON_VERSION }}
          path: dist
      - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          password: ${{ secrets.PYPI_TOKEN }}
