name: "Sync to develop"

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
  workflow_dispatch:

jobs:
  sync_branches:
    runs-on: ubuntu-latest
    concurrency: sync_branches
    name: Sync the branch with the default branch (develop)
    steps:
    - name: Push develop forward (ff only)
      shell: sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        REPOSITORY: ${{ github.repository }}
        TARGET_SHA: ${{ inputs.sha || github.sha }}
      run: |
        REF="refs/heads/${DEFAULT_BRANCH}"
        gh api "/repos/${REPOSITORY}/git/$REF"              \
          --method PATCH                                    \
          --header "Accept: application/vnd.github+json"    \
          --header "X-GitHub-Api-Version: 2022-11-28"       \
          --raw-field sha="${TARGET_SHA}"                   \
          --field force=false
