name: 'Merge Develop into Main Fast Forward Only'

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: '0'
          # The branch you want to checkout (usually equal to `branchtomerge`)
          ref: 'develop'
      - name: Merge Fast Forward
        uses: MaximeHeckel/github-action-merge-fast-forward@v1.1.0
        with:
          # Branch to merge
          branchtomerge: develop
          # Branch that will be updated
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
